### PR TITLE
Updated modal buttons placement

### LINKED ISSUE #63: Rearrange modal buttons
Buttons aren't intuitive and just needs to be cleaned up by position and aesthetically

### PR DESCRIPTION
**Pull request by akath20**
screen shot 2017-04-23 at 10 22 42 pm
Here is the largest change I made to show it all. The rest are simply swapping save/close actions.

The last part I want to fix on this is if you click plan>upload plan, there is no "cancel" button. I tried adding a bootstrap small 'x' to the top right as shown in the bootstrap docs but no luck with it working. When I add "modal" as a class to the div, it freezes the UI and doesn't allow selections. Anyone know why? This closes #63

### CODE REVIEW

**Comment by khanny17** [comment]
The modals here are not only bootstrap modals, but angular ui bootstrap modals. It could be a problem there. 

Most of the modals have the template and a service file to open them in the same folder. I'm not sure how to get the X there, but once you get the element where you want it, add an attribute "ng-click=cancel()" to that tag. Also, make sure that in the accompanying angular file, you are putting the modalInstance.close function on the modalScope. 

Thats a mouthful, but if you can mimic how cancel works with the other modals you can get it to work for the new one

**Review by khanny17 — APPROVED** [review]
Looks good to me, simple fixes all around

**Comment by khanny17** [comment]
Can we merge this bad boy?

**Comment by akath20** [comment]
@khanny17 just need to do that final closing modal, hopefully get it tonight

**Comment by akath20** [comment]
@khanny17 good now

**Pull request merged**
