### PR TITLE
NOT NAVBAR CHANGES

### PR DESCRIPTION
**Pull request by khanny17**
Too lazy to change branch name

This is moving the plan title

image

### CODE REVIEW

**Comment by sklei2** [comment]
Could we make it so the plan title has a little bit more differentiation with the navbar text and the year text (Especially the year text)? Perhaps a different font family/size or bold it? 

Also is there a reason we put it on the left side instead of centered? Just curious if that was decided in a meeting.

**Comment by khanny17** [comment]
It was decided in a meeting to put it on the left side. What is your recommendation for changing the font? Could you actually pull the branch and change it? You can see the relevant files through the diff here

**Comment by sklei2** [comment]
# Updated Plan Title
updated title

- Added some margin on the left.
- Added some margins on the top and bottom. That way we have some differentiation from the navbar as well as the content below.
- Bolded the Text to add some contrast from the Year Headers and add importance.

**Comment by khanny17** [comment]
Dope. We merge?

**Comment by sklei2** [comment]
Just gotta commit it!!

**Review by sklei2 — APPROVED** [review]

**Pull request merged**
