### PR TITLE
Restyling courses

### PR DESCRIPTION
**Pull request by khanny17**
Here's my first pass at the course restyling. What are your two's thoughts? 
@BenAlderfer I know you had some thoughts for what to make the courses look like, how does this compare?

I am 100% open to scrapping this completely OR merging it now but still having plans to rework them further in the future.

image

### CODE REVIEW

**Comment by BenAlderfer** [comment]
That definitely looks better but I'd want to play around with a few small changes to see if I like them better. As for the colors, I think the color picker is nice but I would want easier choices and more precise colors. For most users, preset color options are probably the easiest. I'd also like to have a hex entry or personally define default shades. Maybe look into another color picker like [this one](https://bgrins.github.io/spectrum/). As for the course title bar, not sure how to do this but I think it should be 200 somethings darker than the picked color (see image). Right now I think its a grey partly transparent overlay.

colors

**Comment by BenAlderfer** [comment]
In the linked color picker, I like the right side stuff and I'd like to define nice shades of different colors in the squares on the left which seems possible. See https://bgrins.github.io/spectrum/#options-showPalette

**Comment by khanny17** [comment]
We're gonna stick with the current color picker because it is an angular plugin and not a jquery one. Also i like the color difference you proposed, but after some searching it seems the cleanest way to acheive that effect is definitely the partly transparent gray overlay. We can play with how transparent it is, but forcing it to be 200 darker would involve javascript hacks (which is bad).

**Comment by sklei2** [comment]
I definitely think this is a huge improvement over our current design. I'm not sure if this is the final form, this will require some more investigation, but _definitely_ a step in the right direction. 

From just looking at what we have in the picture:
 - There should be some spacing between the text and the edges of the blocks. We definitely have that in most cases, but it seems like those that are _just_ in the width of the course don't wrap when they should. For example: "Proj Based Calc 1" and the Spring and Summer co-op blocks. Maybe add some padding to force a wrap? However, I am unsure what to do with classes with one long name (see "communication"). In that case I think it is OK as is, but it may be something to consider in the future if we have something longer. Potentially putting a "-" in between the wrap or making the text smaller.
 - The really bright colors are harder to see with the white text, but we already knew this would be an issue. I think it has been brought up that we could change the text color depending on the brightness of it, but that is for the future. For now leaving it as "a user will change it if they can't read it" is OK.
 - In the case of the co-ops do we need the brackets there? If it doesn't have any credits associated with it (null credit class) should those be removed? My initial reaction was to say "make a separate style for it" so it looks like the co-ops on the flowchart, but a null credit class won't always mean "co-op" or takes up the entire semester. That and it is such an edge case that doesn't add any additional information. 

As for the color picker and colors:
 - I definitely agree with @BenAlderfer when it comes to the color picker having some predefined choices. If we want to keep the Javascript picker, would it be possible to wrap that in a modal? So that we can have some predefined choices and have them click on a transparent box or some "add color" button to create their own? Though that would be weird to have modals on modals on modals. This is definitely something we'll need to spike or investigate.
 - I definitely like the grey overlay for the headers. But it seems really odd for the brighter colors (see the yellow and tan). We could change that opacity so that it isn't as overpowering? or changing the header to be a shade of the picked color. 
 - @BenAlderfer made a good point for the header picking. But that would have to be handled by javascript, which I am a little apprehensive about. I wouldn't say completely "bad", but it should be avoided.

**Comment by khanny17** [comment]
I can add 1 or 2 pixels of left/right padding.also I think we might be able to use a css filter instead of a gray overlay. I'll look into it in my next class when I have a computer

**Comment by BenAlderfer** [comment]
The color picker changes are probably outside the scope of this pr. For now I'd like to see that padding and possible course header change. I think it would also be nice to hide the credits brackets if none are entered.

**Comment by khanny17** [comment]
image

1px padding on either side added, changed to use a brightness filter to make the background a darker version of the same color

**Comment by sklei2** [comment]
Looks great!!! Approved!

**Review by sklei2 — APPROVED** [review]

**Pull request merged**
